#!/usr/bin/php -q
<?php
set_time_limit (0);

echo "Loading configuration from mock.conf\n";
$rules = array();
$buffer = null;
foreach (explode("\n", file_get_contents("mock.conf")) as $line) {
  if (trim($line)) {
    if ($buffer) {
      $rules[$buffer] = $line;
      $buffer = null;
    } else {
      $buffer = $line;
    }
  }
}

$address = 'localhost';
$port = 9000;
$verbose = true;

$sock = socket_create(AF_INET, SOCK_STREAM, SOL_TCP);
socket_bind($sock, $address, $port) or die('Could not bind to address');
socket_listen($sock);
echo "Listening on $address:$port\n";

while (true) {
  $client = socket_accept($sock);
  echo "Incomming connection\n";

  $request = socket_read($client, 1024);

  if ($verbose) {
    echo "> ", str_replace("\n", "\n> ", trim($request)) . "\n";
  }

  $response = null;
  foreach ($rules as $pattern => $handler) {
    if (preg_match($pattern, $request)) {
      echo "Matching rule found: $pattern\n";
      $response = file_get_contents($handler);
      break;
    }
  }

  if (!$response) {
    $response = "HTTP/1.1 404 Not Found\n\n";
  }

  if ($verbose) {
    echo "< ", str_replace("\n", "\n< ", trim($response)) . "\n";
  }

  socket_write($client, $response);

  socket_close($client);
}

echo "Shutting down\n";
socket_close($sock);
